# Dictionary of verb tuples -- each entry, organized  by the infinitive, contains a tuple organized in this order: 
# 1 - 1st person singular verb 
# 2 - 2nd person singular verb 
# 3 - 1st person singular preterite 
# 4 - gerund 
# 5 - past participle 


verbs = {
'abajar': (), 
'abalanzar': (), 
'abandonar': (), 
'abducir': (), 
'abnegar': (),
'abrir': ('abro', 'abres', 'abrí', 'abriendo', 'abierto'), 
'alquilar': ('alquilo', 'alquiles', 'alquilé', 'alquilando', 'alquilado'), 
'amar': (), 
'aprobar': (), 
'aumentar': (), 
'averiguar': (), 
'bailar': (), 
'borrar': (), 
'caber': (), 
'caducar': (), 
'caer': (), 
'cocinar':(), 
'comenzar':(), 
'comprar': (), 
'concluir': (), 
'conducir': (), 
'conocer': (), 
'contar': (), 
'contratar': (), 
'convencer': (), 
'convenir': (), 
'crear': (), 
'creer': (), 
'cubrir': (), 
'dar': (), 
'deber': (), 
'decir': (), 
'desear': (), 
'despedir': (), 
'dirigir': (), 
'disminuir': (), 
'dormir': (), 
'echar': (), 
'embalar': (), 
'empeorar': (), 
'emplear': (), 
'enfatizar': (), 
'entender': (), 
'entrar': (), 
'entregar': (), 
'enviar': (), 
'escoger': (), 
'escribir': (), 
'escuchar': (), 
'estar': (), 
'evaluar': (), 
'excluir': (), 
'exportar': (), 
'fabricar': (), 
'gustar': (), 
'haber': (), 
'hacer': (), 
'hipotecar': (), 
'importar': (), 
'imprimir': (), 
'incluir': (), 
'informar': (), 
'involucrar': (), 
'ir': (), 
'lavar': (), 
'leer': (), 
'levantar': (), 
'llamar': (), 
'llegar': (), 
'llenar': (), 
'llevar': (), 
'mandar': (), 
'manejar': (), 
'mantener': (), 
'matar': (), 
'medir': (), 
'mejorar': (), 
'mentir': (), 
'meter': (), 
'mirar': (), 
'morir': (), 
'necesitar': (), 
'odiar': (), 
'oír': (), 
'pagar': (), 
'parecer': (), 
'pedir': (), 
'pegar': (), 
'pensar': (), 
'perdonar': (), 
'permitir': (), 
'pesar': (), 
'poder': (), 
'poner': (), 
'postergar': (), 
'predecir': (), 
'preguntar': (),
'preparar': ('preparo', 'preparas', 'preparé', 'preparando', 'preparado'), 
'prever': (), 
'producir': (), 
'querer': (), 
'quitar': (),
'redactar': (), 
'reducir': (), 
'relatar': (), 
'rendir': (), 
'repetir': (),
'revisar': (), 
'romper': (), 
'saber': (), 
'sacar': (), 
'salir': (),
'seguir': (), 
'ser': (), 
'sentarse': (), 
'servir': (), 
'sobornar': (),
'tachar': (), 
'tener': (), 
'traducir': (), 
'traer': (), 
'usar': (),
'utilizar': (), 
'vacar': (), 
'vaciarse': (), 
'vacunar': (), 
'vencer': (), 
'vender': ('vendo', 'vendes', 'vendí', 'vendiendo', 'vendido'), 
'venir': (), 
'ver': (), 
'versar': (), 
'verificar': (), 
'volver': ('vuelvo', 'vuelves', 'volver', 'volví', 'volviendo', 'vuelto'), 
'yapar': (), 
'yermar': (), 
'yuxtaponer': (),
'zafar': (), 
'zaherir': (), 
'zahondar': (), 
'zambullir': (), 
'zampar': (),

}
    