# Dictionary of verb tuples -- each entry, organized  by the infinitive, contains a tuple organized in this order: 
# 1 - 1st person singular verb 
# 2 - 2nd person singular verb 
# 3 - 1st person singular preterite 
# 4 - gerund 
# 5 - past participle 


verbs = {
'abajar': (), 
'abalanzar': (), 
'abandonar': (), 
'abducir': (), 
'abnegar': (),
'abrir': ('abro', 'abres', 'abrí', 'abriendo', 'abierto'), 
'alquilar': ('alquilo', 'alquiles', 'alquilé', 'alquilando', 'alquilado'), 
'amar': ('amo', 'amas', 'amé', 'amando', 'amado'), 
'aprobar': ('apruebo', 'apruebas', 'aprobé', 'aprobando', 'aprobado'), 
'aumentar': ('aumento', 'aumentas', 'aumenté', 'aumentando', 'aumentado'), 
'averiguar': ('averiguo', 'averiguas', 'averigüé', 'averiguando', 'averiguado'), 
'bailar': ('bailo', 'bailas', 'bailé', 'bailando', 'bailado'), 
'borrar': ('borro', 'borras', 'borré', 'borrando', 'borrado'), 
'caber': ('quepo', 'cabes', 'cupe', 'cabiendo', 'cabido'), 
'caducar': (), 
'caer': ('caigo', 'caes', 'caí', 'cayendo', 'caído'), 
'cocinar':('cocino', 'cocinas', 'cociné', 'cocinando', 'cocinado'), 
'comenzar':('comienzo', 'comienzas', 'comencé', 'comenzando', 'comenzado'), 
'comprar': ('compro', 'compras', 'compré', 'comprando', 'comprado'), 
'concluir': ('concluyo', 'concluyes', 'concluí', 'concluyendo', 'concluido'), 
'conducir': ('conduzco', 'conduces', 'conduje', 'conduciendo', 'conducido'), 
'conocer': ('conozco', 'conoces', 'conocí', 'conociendo', 'conocido'), 
'contar': (), 
'contratar': (), 
'convencer': (), 
'convenir': (), 
'crear': (), 
'creer': (), 
'cubrir': (), 
'dar': (), 
'deber': (), 
'decir': (), 
'desear': (), 
'despedir': (), 
'dirigir': (), 
'disminuir': (), 
'dormir': (), 
'echar': (), 
'embalar': (), 
'empeorar': (), 
'emplear': (), 
'enfatizar': (), 
'entender': (), 
'entrar': (), 
'entregar': (), 
'enviar': (), 
'escoger': (), 
'escribir': (), 
'escuchar': (), 
'estar': (), 
'evaluar': (), 
'excluir': (), 
'exportar': (), 
'fabricar': (), 
'gustar': (), 
'haber': (), 
'hacer': (), 
'hipotecar': (), 
'importar': (), 
'imprimir': (), 
'incluir': (), 
'informar': (), 
'involucrar': (), 
'ir': (), 
'lavar': (), 
'leer': (), 
'levantar': (), 
'llamar': (), 
'llegar': (), 
'llenar': (), 
'llevar': (), 
'mandar': (), 
'manejar': (), 
'mantener': (), 
'matar': (), 
'medir': (), 
'mejorar': (), 
'mentir': (), 
'meter': (), 
'mirar': (), 
'morir': (), 
'necesitar': (), 
'odiar': (), 
'oír': (), 
'pagar': (), 
'parecer': (), 
'pedir': (), 
'pegar': (), 
'pensar': (), 
'perdonar': (), 
'permitir': (), 
'pesar': (), 
'poder': (), 
'poner': (), 
'postergar': (), 
'predecir': (), 
'preguntar': (),
'preparar': ('preparo', 'preparas', 'preparé', 'preparando', 'preparado'), 
'prever': (), 
'producir': (), 
'querer': (), 
'quitar': (),
'redactar': (), 
'reducir': (), 
'relatar': (), 
'rendir': (), 
'repetir': (),
'revisar': (), 
'romper': (), 
'saber': (), 
'sacar': (), 
'salir': (),
'seguir': (), 
'ser': (), 
'sentarse': (), 
'servir': (), 
'sobornar': ('soborno', 'sobornas', 'sorborné', 'sobornando', 'sobornado'),
'tachar': ('tacho', 'tachas', 'taché', 'tachando', 'tachado'), 
'tener': ('tengo', 'tienes', 'tuve', 'teniendo', 'tenido'), 
'traducir': ('traduzco', 'traduces', 'traduje', 'traduciendo', 'traducido'), 
'traer': ('traigo', 'traes', 'traje', 'trayendo', 'traído'), 
'usar': ('uso', 'usas', 'usé', 'usando', 'usado'),
'utilizar': ('utilizo', 'utilizas', 'utilicé', 'utilizando', 'utilizado'), 
'vacar': (), 
'vaciarse': (), 
'vacunar': (), 
'vencer': ('venzo', 'vences', 'vencí', 'venciendo', 'vencido'), 
'vender': ('vendo', 'vendes', 'vendí', 'vendiendo', 'vendido'), 
'venir': ('vengo', 'vienes', 'vine', 'viniendo', 'venido'), 
'ver': ('veo', 'ves', 'vi', 'viendo', 'visto'), 
'versar': (''), 
'verificar': ('verifico', 'verificas', 'verifiqué', 'verificando', 'verificado'), 
'volver': ('vuelvo', 'vuelves', 'volver', 'volví', 'volviendo', 'vuelto'), 
'yapar': (), 
'yermar': (), 
'yuxtaponer': (),
'zafar': (), 
'zaherir': (), 
'zahondar': (), 
'zambullir': (), 
'zampar': (),

}
    